// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTestTopModule.h for the primary calling header

#ifndef VERILATED_VTESTTOPMODULE___024ROOT_H_
#define VERILATED_VTESTTOPMODULE___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"


class VTestTopModule__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTestTopModule___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb_clock;
        VL_IN8(reset,0,0);
        VL_IN8(io_regs_debug_read_address,4,0);
        CData/*1:0*/ TestTopModule__DOT__CPU_clkdiv;
        CData/*1:0*/ TestTopModule__DOT___CPU_next_T_2;
        CData/*0:0*/ TestTopModule__DOT__read_pending;
        CData/*0:0*/ TestTopModule__DOT__mem__DOT__mem_0_MPORT_en;
        CData/*0:0*/ TestTopModule__DOT__rom_loader__DOT__valid;
        CData/*0:0*/ TestTopModule__DOT__rom_loader__DOT___GEN_0;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master_io_bundle_read;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master_io_bundle_write;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ctrl_io_jump_flag;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ctrl_io_jump_instruction_id;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ctrl_io_pc_stall;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ctrl_io_branch_hazard;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch_io_btb_mispredict;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch_io_btb_correct_prediction;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id_io_interrupt_assert;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__btb_non_branch;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__btb_wrong_target;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb_io_predicted_taken;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb_io_update_valid;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb_io_update_taken;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__pending_jump;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__prev_jump_flag;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT___GEN_1;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_0;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_1;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_2;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_3;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_4;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_5;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_6;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_7;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_8;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_9;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_10;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_11;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_12;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_13;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_14;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__valid_15;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_48;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_49;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_50;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_51;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_52;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_53;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_54;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_55;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_56;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_57;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_58;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_59;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_60;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_61;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_62;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_63;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_127;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_128;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_129;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_130;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_131;
    };
    struct {
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_132;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_133;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_134;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_135;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_136;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_137;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_138;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_139;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_140;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_141;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_142;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_143;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__instruction_io_stall;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__instruction_io_flush;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__btb_predicted_taken__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__btb_predicted_taken__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id__DOT___uses_rs1_T_4;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id__DOT___io_ctrl_jump_instruction_T_2;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__instruction_io_stall;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__instruction_io_flush;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_reg1_read_address_io_in;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_reg2_read_address_io_in;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_reg1_read_address__DOT__myreg;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_reg1_read_address__DOT__out;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_reg2_read_address__DOT__myreg;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_reg2_read_address__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_write_enable__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_write_enable__DOT__out;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_write_address__DOT__myreg;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_write_address__DOT__out;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_write_source__DOT__myreg;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__regs_write_source__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__aluop1_source__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__aluop1_source__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__aluop2_source__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__aluop2_source__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__csr_write_enable__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__csr_write_enable__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__memory_read_enable__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__memory_read_enable__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__memory_write_enable__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__memory_write_enable__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__regs_write_enable__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__regs_write_enable__DOT__out;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__regs_write_source__DOT__myreg;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__regs_write_source__DOT__out;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__regs_write_address__DOT__myreg;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__regs_write_address__DOT__out;
        CData/*2:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__funct3__DOT__myreg;
        CData/*2:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__funct3__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__memory_read_enable__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__memory_read_enable__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__memory_write_enable__DOT__myreg;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__memory_write_enable__DOT__out;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT__mem_access_state;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT__latched_regs_write_source;
        CData/*2:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT__latched_funct3;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT__latched_address_index;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT___GEN_7;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT___GEN_21;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT___GEN_24;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT___GEN_38;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__regs_write_source_io_in;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__regs_write_enable__DOT__myreg;
    };
    struct {
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__regs_write_enable__DOT__out;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__regs_write_source__DOT__myreg;
        CData/*1:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__regs_write_source__DOT__out;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__regs_write_address__DOT__myreg;
        CData/*4:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__regs_write_address__DOT__out;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint__DOT____VdfgTmp_h7e083cbd__0;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint__DOT____VdfgTmp_hb487e99f__0;
        CData/*2:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__state;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__read_valid;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__ARVALID;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__RREADY;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__write_valid;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__write_strobe_0;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__write_strobe_1;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__write_strobe_2;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__write_strobe_3;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__AWVALID;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__WVALID;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__BREADY;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_6;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_7;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_10;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_11;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_23;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_25;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_26;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_27;
        CData/*2:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_29;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_36;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_37;
        CData/*0:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_38;
        CData/*2:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT___GEN_39;
        CData/*2:0*/ TestTopModule__DOT__mem_slave__DOT__state;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__read;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__ARREADY;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__RVALID;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__write;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__write_strobe_0;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__write_strobe_1;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__write_strobe_2;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__write_strobe_3;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__AWREADY;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__WREADY;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT__BVALID;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_1;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_3;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_7;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_12;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_13;
        CData/*2:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_14;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_44;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_45;
        CData/*2:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_46;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_48;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_49;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_50;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_51;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_52;
        CData/*0:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_53;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb_clock__0;
        CData/*0:0*/ __VactContinue;
    };
    struct {
        VL_IN16(io_csr_debug_read_address,11,0);
        SData/*12:0*/ TestTopModule__DOT__mem__DOT__mem_0_io_bundle_read_data_MPORT_addr_pipe_0;
        SData/*12:0*/ TestTopModule__DOT__mem__DOT__mem_1_io_bundle_read_data_MPORT_addr_pipe_0;
        SData/*12:0*/ TestTopModule__DOT__mem__DOT__mem_2_io_bundle_read_data_MPORT_addr_pipe_0;
        SData/*12:0*/ TestTopModule__DOT__mem__DOT__mem_3_io_bundle_read_data_MPORT_addr_pipe_0;
        SData/*12:0*/ TestTopModule__DOT__mem__DOT__mem_3_io_debug_read_data_MPORT_addr_pipe_0;
        SData/*12:0*/ TestTopModule__DOT__mem__DOT__mem_3_io_instruction_MPORT_addr_pipe_0;
        SData/*11:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__csr_address__DOT__myreg;
        SData/*11:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__csr_address__DOT__out;
        VL_IN(io_mem_debug_read_address,31,0);
        VL_OUT(io_regs_debug_read_data,31,0);
        VL_OUT(io_mem_debug_read_data,31,0);
        VL_OUT(io_csr_debug_read_data,31,0);
        VL_IN(io_interrupt_flag,31,0);
        IData/*31:0*/ TestTopModule__DOT__mem_io_bundle_address;
        IData/*31:0*/ TestTopModule__DOT__mem_io_bundle_write_data;
        IData/*31:0*/ TestTopModule__DOT__rom_loader__DOT__address;
        IData/*31:0*/ TestTopModule__DOT__rom_loader__DOT___address_T_1;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs_io_write_data;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id_io_clint_jump_address;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex_io_csr_write_data;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint_io_csr_bundle_mstatus;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint_io_csr_bundle_mepc;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint_io_csr_bundle_mtvec;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint_io_csr_bundle_mie;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint_io_csr_bundle_mcause_write_data;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_0;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_1;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_2;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_3;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_4;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_5;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_6;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_7;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_8;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_9;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_10;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_11;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_12;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_13;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_14;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_15;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_16;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_17;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_18;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_19;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_20;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_21;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_22;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_23;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_24;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_25;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_26;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_27;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_28;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_29;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__regs__DOT__registers_30;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb_io_predicted_pc;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb_io_update_target;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__pc;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__pending_jump_addr;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__prev_jump_addr;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT___next_pc_T_5;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_0;
    };
    struct {
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_1;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_2;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_3;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_4;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_5;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_6;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_7;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_8;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_9;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_10;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_11;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_12;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_13;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_14;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__tags_15;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_0;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_1;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_2;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_3;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_4;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_5;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_6;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_7;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_8;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_9;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_10;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_11;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_12;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_13;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_14;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT__targets_15;
        IData/*25:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__inst_fetch__DOT__btb__DOT___GEN_111;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__instruction_io_in;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__instruction__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__instruction__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__instruction_address__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__instruction_address__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__btb_predicted_target__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__if2id__DOT__btb_predicted_target__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id__DOT___branch_taken_T_7;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id__DOT___branch_taken_T_8;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__reg1_data_io_in;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__reg2_data_io_in;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__immediate_io_in;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__csr_read_data_io_in;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__instruction__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__instruction__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__instruction_address__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__instruction_address__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__reg1_data__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__reg1_data__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__reg2_data__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__reg2_data__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__immediate__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__immediate__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__csr_read_data__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__id2ex__DOT__csr_read_data__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex__DOT__alu_io_result;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__reg2_data_io_in;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__instruction_address__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__instruction_address__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__reg2_data__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__reg2_data__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__alu_result__DOT__myreg;
    };
    struct {
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__alu_result__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__csr_read_data__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__ex2mem__DOT__csr_read_data__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT__latched_memory_read_data;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem__DOT___processed_data_T_65;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__memory_read_data_io_in;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__alu_result__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__alu_result__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__memory_read_data__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__memory_read_data__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__instruction_address__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__instruction_address__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__csr_read_data__DOT__myreg;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__mem2wb__DOT__csr_read_data__DOT__out;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint__DOT__instruction_address;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__clint__DOT__mstatus_disable_interrupt;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT__mstatus;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT__mie;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT__mtvec;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT__mscratch;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT__mepc;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT__mcause;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT___GEN_1;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT___GEN_2;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT___GEN_12;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__addr;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__read_data;
        IData/*31:0*/ TestTopModule__DOT__cpu__DOT__axi_master__DOT__write_data;
        IData/*31:0*/ TestTopModule__DOT__mem_slave__DOT__addr;
        IData/*31:0*/ TestTopModule__DOT__mem_slave__DOT__read_data;
        IData/*31:0*/ TestTopModule__DOT__mem_slave__DOT__write_data;
        IData/*31:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_9;
        IData/*31:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_43;
        IData/*31:0*/ TestTopModule__DOT__mem_slave__DOT___GEN_47;
        IData/*31:0*/ __Vdly__TestTopModule__DOT__rom_loader__DOT__address;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT__cycles;
        QData/*63:0*/ TestTopModule__DOT__cpu__DOT__cpu__DOT__csr_regs__DOT___cycles_T_1;
        VlUnpacked<CData/*7:0*/, 8192> TestTopModule__DOT__mem__DOT__mem_0;
        VlUnpacked<CData/*7:0*/, 8192> TestTopModule__DOT__mem__DOT__mem_1;
        VlUnpacked<CData/*7:0*/, 8192> TestTopModule__DOT__mem__DOT__mem_2;
        VlUnpacked<CData/*7:0*/, 8192> TestTopModule__DOT__mem__DOT__mem_3;
        VlUnpacked<IData/*31:0*/, 399> TestTopModule__DOT__instruction_rom__DOT__mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    VTestTopModule__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTestTopModule___024root(VTestTopModule__Syms* symsp, const char* v__name);
    ~VTestTopModule___024root();
    VL_UNCOPYABLE(VTestTopModule___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(uint32_t* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
};


#endif  // guard
